apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-k8s-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project-k8s-deployment
  template:
    metadata:
      labels:
        app: project-k8s-deployment
    spec:
      containers:
      - name: project-k8s-deployment
        image: registry.gitlab.com/tampoohoonm/php-test-project:latest
        ports:
        - containerPort: 8000


---

apiVersion: v1
kind: Service
metadata:
  name: project-k8s-deployment
spec:
  type: LoadBalancer
  selector:
    app: project-k8s-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000 #container port
    nodePort: 30080



